name: NanoPi-R2S RK3328 OpenWrt 19.07 Build

on:
  push:
    branches: 
      - master
      -
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"

          sudo apt-get update
          sudo apt-get -y install upx-ucl unzip
          sudo apt-get -y dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash

      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Download Source
        run: |
          rm -rf friendlywrt-rk3328
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          repo sync -c  --no-clone-bundle

      - name: Build OpenWrt
        run: |
          cd friendlywrt-rk3328
          ./build.sh nanopi_r2s.mk
