name: NanoPi R2S FriendlyWrt Build

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          git config --global user.email "chinaluopiao@gmail.com" && git config --global user.name "luopiao"
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash

      - name: Install Repo
        run: |
          sudo -E  apt-get install repo

      - name: Download Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v22.03 -m rk3328.xml  --no-clone-bundle
          repo sync -c  --no-clone-bundle


      - name: Update Feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a


      - name: Write Config
        run: |
          cd friendlywrt-rk3328
          ls -lsh 
          echo "CONFIG_PACKAGE_iptables-mod-tproxy=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_iptables=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_dnsmasq-full=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_coreutils=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_coreutils-nohup=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_bash=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_libcurl=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_jsonfilter=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_ca-certificates=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_ipset=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_ip-full=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_iptables-mod-extra=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_libcap-bin=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_kmod-fs-ext4=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_kmod-fs-ntfs=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_kmod-fs-vfat=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_kmod-tun=y" >> configs/config_rk3328
          cat configs/config_rk3328

      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          ./build.sh nanopi_r2s.mk

      - name: Assemble Artifact
        run: |
          mkdir -p ./artifact/
          find friendlywrt-rk3328/out/ -name "FriendlyWrt_*img*" | xargs -I{} sh -c 'f=$(basename $1); zip -r -j "./artifact/${f}.zip" $1' sh {} \;
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FriendlyWrt-NanoPi-R2S
          path: |
            artifact